//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSURLSessionTask;

@interface AnnotatedTask : NSObject
{
    BOOL _isInAForegroundQueue;
    NSURLSessionTask *_task;
}

+ (id)annotatedTaskWithTask:(id)arg1 isInAForegroundQueue:(BOOL)arg2;
@property(nonatomic) BOOL isInAForegroundQueue; // @synthesize isInAForegroundQueue=_isInAForegroundQueue;
@property(retain, nonatomic) NSURLSessionTask *task; // @synthesize task=_task;
- (void).cxx_destruct;

@end

