//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIActivity.h"

@class NSString, NSURL;

@interface FCAddToInstapaperActivity : UIActivity
{
    NSURL *_URL;
    NSString *_xCallbackSource;
    NSURL *_xCallbackSuccessURL;
}

+ (id)instapaperLogoWithHeight:(float)arg1;
@property(retain, nonatomic) NSURL *xCallbackSuccessURL; // @synthesize xCallbackSuccessURL=_xCallbackSuccessURL;
@property(copy, nonatomic) NSString *xCallbackSource; // @synthesize xCallbackSource=_xCallbackSource;
@property(retain, nonatomic) NSURL *URL; // @synthesize URL=_URL;
- (void).cxx_destruct;
- (void)performActivity;
- (void)prepareWithActivityItems:(id)arg1;
- (BOOL)canPerformWithActivityItems:(id)arg1;
- (id)activityImage;
- (id)activityTitle;
- (id)activityType;
- (id)initWithSourceName:(id)arg1 successCallbackURL:(id)arg2;

@end

