//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIAlertView.h"

#import "UIAlertViewDelegate.h"

@class NSMutableDictionary;

@interface FCAlertView : UIAlertView <UIAlertViewDelegate>
{
    CDUnknownBlockType _cancelButtonBlock;
    NSMutableDictionary *_otherButtonBlocks;
}

@property(retain, nonatomic) NSMutableDictionary *otherButtonBlocks; // @synthesize otherButtonBlocks=_otherButtonBlocks;
@property(copy, nonatomic) CDUnknownBlockType cancelButtonBlock; // @synthesize cancelButtonBlock=_cancelButtonBlock;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)show;
- (void)addButtonWithTitle:(id)arg1 action:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (id)initWithTitle:(id)arg1 message:(id)arg2 cancelButtonTitle:(id)arg3 cancelBlock:(CDUnknownBlockType)arg4;

@end

