//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

@class NSArray;

@interface FCPickerViewController : UITableViewController
{
    unsigned int _currentSelection;
    NSArray *_items;
    CDUnknownBlockType _itemLabelBlock;
    CDUnknownBlockType _pickedBlock;
}

@property(copy, nonatomic) CDUnknownBlockType pickedBlock; // @synthesize pickedBlock=_pickedBlock;
@property(copy, nonatomic) CDUnknownBlockType itemLabelBlock; // @synthesize itemLabelBlock=_itemLabelBlock;
@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)configureCell:(id)arg1 withItem:(id)arg2;
- (void)configureTableView:(id)arg1 withCellReuseIdentifier:(id)arg2;
- (void)viewDidLoad;
- (id)initWithTitle:(id)arg1 items:(id)arg2 itemLabelBlock:(CDUnknownBlockType)arg3 pickedBlock:(CDUnknownBlockType)arg4 currentSelection:(unsigned int)arg5;

@end

