//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLConnectionDataDelegate.h"
#import "NSURLConnectionDelegate.h"

@class NSArray, NSError, NSHTTPURLResponse, NSMutableData, NSObject<OS_dispatch_semaphore>, NSURLRequest;

@interface FCSecureConnection : NSObject <NSURLConnectionDelegate, NSURLConnectionDataDelegate>
{
    NSObject<OS_dispatch_semaphore> *urlConnectionDoneSemaphore;
    NSHTTPURLResponse *_response;
    NSError *_error;
    NSMutableData *_data;
    NSArray *_keys;
    NSURLRequest *_originalRequest;
}

+ (id)keysFromCertificates:(id)arg1;
+ (id)sendSynchronousRequest:(id)arg1 returningResponse:(id *)arg2 error:(id *)arg3 permittedKeys:(id)arg4;
@property(copy, nonatomic) NSURLRequest *originalRequest; // @synthesize originalRequest=_originalRequest;
@property(copy, nonatomic) NSArray *keys; // @synthesize keys=_keys;
@property(retain, nonatomic) NSMutableData *data; // @synthesize data=_data;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) NSHTTPURLResponse *response; // @synthesize response=_response;
- (void).cxx_destruct;
- (void)connection:(id)arg1 willSendRequestForAuthenticationChallenge:(id)arg2;
- (BOOL)connectionShouldUseCredentialStorage:(id)arg1;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (id)initWithRequest:(id)arg1 returningResponse:(id *)arg2 error:(id *)arg3 permittedKeys:(id)arg4;

@end

