//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface OCAPIConnection : NSObject
{
}

+ (void)showRateLimitAlert;
+ (void)showSSLPinningAlert;
+ (void)showAPIErrorAlert;
+ (void)startITunesLookupRequestWithArguments:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)startITunesSearchRequestWithArguments:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)startStaticAPIRequestWithAction:(id)arg1 arguments:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)startRequestWithMethod:(id)arg1 controller:(id)arg2 action:(id)arg3 arguments:(id)arg4 requestBody:(id)arg5 completion:(CDUnknownBlockType)arg6;
+ (id)_synchronousRequestWithMethod:(id)arg1 host:(id)arg2 controller:(id)arg3 action:(id)arg4 arguments:(id)arg5 requestBody:(id)arg6 sendToken:(BOOL)arg7 pin:(BOOL)arg8 apiError:(int *)arg9 connectionError:(id *)arg10;
+ (id)sendSynchronousRequestWithMethod:(id)arg1 controller:(id)arg2 action:(id)arg3 arguments:(id)arg4 requestBody:(id)arg5 apiError:(int *)arg6 connectionError:(id *)arg7;
+ (id)_requestWithMethod:(id)arg1 host:(id)arg2 controller:(id)arg3 action:(id)arg4 arguments:(id)arg5 requestBody:(id)arg6 sendToken:(BOOL)arg7;
+ (id)requestWithMethod:(id)arg1 controller:(id)arg2 action:(id)arg3 arguments:(id)arg4 requestBody:(id)arg5;
+ (id)downloadableURLForUploadedFileURLString:(id)arg1;
+ (void)setLoginToken:(id)arg1;
+ (id)loginToken;

@end

