//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@class NSString;

@interface OCArtworkView : UIImageView
{
    CDUnknownBlockType _newImageLoadedBlock;
    NSString *_imageAccessibilityLabel;
    NSString *_identifier;
}

+ (void)invalidateArtworkForIdentifier:(id)arg1;
+ (id)imageDataForIdentifier:(id)arg1 targetWidth:(int)arg2 resultingWidth:(int *)arg3;
+ (id)imageDataForIdentifier:(id)arg1 exactWidth:(int)arg2;
+ (void)saveImageData:(id)arg1 forIdentifier:(id)arg2 width:(int)arg3;
+ (id)sizesForIdentifier:(id)arg1;
+ (void)closeDatabase;
+ (id)databaseQueue;
+ (id)resizeQueue;
+ (void)setFullSizeImageBlock:(CDUnknownBlockType)arg1;
+ (void)invalidateCachedImagesForIdentifier:(id)arg1;
+ (id)cachedImageForWidth:(int)arg1 identifier:(id)arg2;
+ (void)cacheImage:(id)arg1 forWidth:(int)arg2 identifier:(id)arg3;
+ (void)generateStandardWidthsForImage:(id)arg1 identifier:(id)arg2;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(copy, nonatomic) NSString *imageAccessibilityLabel; // @synthesize imageAccessibilityLabel=_imageAccessibilityLabel;
@property(copy, nonatomic) CDUnknownBlockType newImageLoadedBlock; // @synthesize newImageLoadedBlock=_newImageLoadedBlock;
- (void).cxx_destruct;
- (void)loadImage;
@property(copy, nonatomic) NSString *imageIdentifier;
- (void)artworkDataChanged:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

