//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSURL;

@interface OCAudioFileReader : NSObject
{
    float readBuffer[44100];
    long long _totalFrames;
    long long _tellOffsetCorrection;
    double sampleRate;
    struct OpaqueExtAudioFile *audioFileRef;
    struct OpaqueAudioFileID *audioFileID;
    int extAFReachedEOF;
    int extAFNumChannels;
    NSURL *_fileURL;
    int _outputChannels;
    long long _currentFrame;
    struct AudioStreamBasicDescription _streamDescription;
    struct AudioStreamBasicDescription _outputStreamDescription;
}

@property(readonly, nonatomic) int outputChannels; // @synthesize outputChannels=_outputChannels;
@property(retain, nonatomic) NSURL *fileURL; // @synthesize fileURL=_fileURL;
@property(readonly, nonatomic) struct AudioStreamBasicDescription outputStreamDescription; // @synthesize outputStreamDescription=_outputStreamDescription;
@property(readonly, nonatomic) struct AudioStreamBasicDescription streamDescription; // @synthesize streamDescription=_streamDescription;
@property(readonly, nonatomic) long long totalFrames; // @synthesize totalFrames=_totalFrames;
@property(nonatomic) long long currentFrame; // @synthesize currentFrame=_currentFrame;
- (void).cxx_destruct;
@property(readonly, nonatomic) double sampleRate;
- (void)seekToFrame:(long long)arg1;
- (unsigned long)readSamples:(long long)arg1 intoArray:(float **)arg2 error:(int *)arg3 reachedEOF:(char *)arg4;
- (unsigned long)readSamples:(long long)arg1 intoArray:(float **)arg2 error:(int *)arg3;
- (BOOL)openAudioFile:(id)arg1 outputChannels:(int)arg2;
- (BOOL)openAudioFile:(id)arg1;
- (void)dealloc;
- (id)init;

@end

