//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CALayer, UIToolbar;

@interface OCBlurView : UIView
{
    UIToolbar *_blurToolbar;
    CALayer *_blurLayer;
    UIView *_blurView;
}

@property(retain, nonatomic) UIView *blurView; // @synthesize blurView=_blurView;
@property(retain, nonatomic) CALayer *blurLayer; // @synthesize blurLayer=_blurLayer;
@property(retain, nonatomic) UIToolbar *blurToolbar; // @synthesize blurToolbar=_blurToolbar;
- (void).cxx_destruct;
- (void)didInit;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

@end

