//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITextFieldDelegate.h"

@class UITextField;

@interface OCDeleteAccountViewController : UIViewController <UITextFieldDelegate>
{
    UITextField *_passwordField;
}

@property(retain, nonatomic) UITextField *passwordField; // @synthesize passwordField=_passwordField;
- (void).cxx_destruct;
- (void)deleteButtonTapped:(id)arg1;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)cancel:(id)arg1;
- (id)init;

@end

