//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class NSArray, OCStyledLabel, UIImage;

@interface OCDirectoryCategoryCollectionViewCell : UICollectionViewCell
{
    int columns;
    OCStyledLabel *_titleLabel;
    NSArray *_artworkImageViews;
    UIImage *_placeholderArtworkImage;
}

+ (int)rows;
+ (int)columns;
+ (float)titleLabelHeight;
+ (float)heightForWidth:(float)arg1;
+ (id)placeholderImage;
@property(retain, nonatomic) UIImage *placeholderArtworkImage; // @synthesize placeholderArtworkImage=_placeholderArtworkImage;
@property(copy, nonatomic) NSArray *artworkImageViews; // @synthesize artworkImageViews=_artworkImageViews;
@property(retain, nonatomic) OCStyledLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)configureWithCategoryTitle:(id)arg1 feeds:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

