//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FCTableViewControllerWithDeselectionFix.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextFieldDelegate.h"

@class NSArray, OCPlaylist, UITextField;

@interface OCEditPlaylistViewController : FCTableViewControllerWithDeselectionFix <UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate>
{
    BOOL initialCreationMode;
    BOOL includedFeedsMode;
    BOOL userPickedExcludedFeedsMode;
    BOOL animatingTableDataChange;
    unsigned int userUpdateWindowIdx;
    UITextField *_titleTextField;
    OCPlaylist *_playlist;
    NSArray *_playlistPriorityFeeds;
    NSArray *_playlistIncludedFeeds;
    NSArray *_playlistExcludedFeeds;
    NSArray *_playlistIncludedItems;
    NSArray *_playlistExcludedItems;
    NSArray *_allFeedsAvailable;
    NSArray *_playlistAvailableFeeds;
    NSArray *_playlistAvailablePriorityFeeds;
    NSArray *_playlistAvailableItemsForInclusion;
    NSArray *_playlistAvailableItemsForExclusion;
    NSArray *_sortDescriptions;
    NSArray *_itemStatusDescriptions;
    NSArray *_userUpdateWindowDurations;
    NSArray *_userUpdateWindowDescriptions;
}

@property(copy, nonatomic) NSArray *userUpdateWindowDescriptions; // @synthesize userUpdateWindowDescriptions=_userUpdateWindowDescriptions;
@property(copy, nonatomic) NSArray *userUpdateWindowDurations; // @synthesize userUpdateWindowDurations=_userUpdateWindowDurations;
@property(copy, nonatomic) NSArray *itemStatusDescriptions; // @synthesize itemStatusDescriptions=_itemStatusDescriptions;
@property(copy, nonatomic) NSArray *sortDescriptions; // @synthesize sortDescriptions=_sortDescriptions;
@property(copy, nonatomic) NSArray *playlistAvailableItemsForExclusion; // @synthesize playlistAvailableItemsForExclusion=_playlistAvailableItemsForExclusion;
@property(copy, nonatomic) NSArray *playlistAvailableItemsForInclusion; // @synthesize playlistAvailableItemsForInclusion=_playlistAvailableItemsForInclusion;
@property(copy, nonatomic) NSArray *playlistAvailablePriorityFeeds; // @synthesize playlistAvailablePriorityFeeds=_playlistAvailablePriorityFeeds;
@property(copy, nonatomic) NSArray *playlistAvailableFeeds; // @synthesize playlistAvailableFeeds=_playlistAvailableFeeds;
@property(copy, nonatomic) NSArray *allFeedsAvailable; // @synthesize allFeedsAvailable=_allFeedsAvailable;
@property(copy, nonatomic) NSArray *playlistExcludedItems; // @synthesize playlistExcludedItems=_playlistExcludedItems;
@property(copy, nonatomic) NSArray *playlistIncludedItems; // @synthesize playlistIncludedItems=_playlistIncludedItems;
@property(copy, nonatomic) NSArray *playlistExcludedFeeds; // @synthesize playlistExcludedFeeds=_playlistExcludedFeeds;
@property(copy, nonatomic) NSArray *playlistIncludedFeeds; // @synthesize playlistIncludedFeeds=_playlistIncludedFeeds;
@property(copy, nonatomic) NSArray *playlistPriorityFeeds; // @synthesize playlistPriorityFeeds=_playlistPriorityFeeds;
@property(retain, nonatomic) OCPlaylist *playlist; // @synthesize playlist=_playlist;
@property(retain, nonatomic) UITextField *titleTextField; // @synthesize titleTextField=_titleTextField;
- (void).cxx_destruct;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 targetIndexPathForMoveFromRowAtIndexPath:(id)arg2 toProposedIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)reloadData;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)viewDidLoad;
- (void)saveAndDismiss:(id)arg1;
- (void)cancelInitialCreation:(id)arg1;
- (void)dealloc;
- (id)initWithPlaylist:(id)arg1 initialCreationMode:(BOOL)arg2;

@end

