//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSString, OCArtworkView, OCFeedItem, OCPeakMetersView, OCStyledLabel, OCViewStack, UIButton;

@interface OCEpisodeCell : UITableViewCell
{
    BOOL showArtwork;
    BOOL isInDownloadsWindow;
    int currentNowPlayingTimestamp;
    BOOL currentTouchIsSwipe;
    BOOL isShowingDeleteButton;
    id <OCEpisodeCellInfoDelegate> _infoDelegate;
    id <OCEpisodeCellDownloadDelegate> _downloadDelegate;
    OCFeedItem *_item;
    OCArtworkView *_albumArtImageView;
    OCPeakMetersView *_peakMetersView;
    NSString *_dateDisplayString;
    NSString *_durationDisplayString;
    OCViewStack *_viewStack;
    OCStyledLabel *_titleLabel;
    OCStyledLabel *_statusLabel;
    OCStyledLabel *_descriptionLabel;
    UIButton *_infoButton;
    UIButton *_downloadRetryButton;
    UIButton *_downloadPauseButton;
}

+ (id)displayStringForDuration:(int)arg1 remaining:(BOOL)arg2;
+ (void)setVisualizersPaused:(BOOL)arg1;
+ (float)standardHeightWithExtendedDescription;
+ (float)standardHeightWithDescription;
+ (float)standardHeight;
@property(retain, nonatomic) UIButton *downloadPauseButton; // @synthesize downloadPauseButton=_downloadPauseButton;
@property(retain, nonatomic) UIButton *downloadRetryButton; // @synthesize downloadRetryButton=_downloadRetryButton;
@property(retain, nonatomic) UIButton *infoButton; // @synthesize infoButton=_infoButton;
@property(retain, nonatomic) OCStyledLabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) OCStyledLabel *statusLabel; // @synthesize statusLabel=_statusLabel;
@property(retain, nonatomic) OCStyledLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) OCViewStack *viewStack; // @synthesize viewStack=_viewStack;
@property(copy, nonatomic) NSString *durationDisplayString; // @synthesize durationDisplayString=_durationDisplayString;
@property(copy, nonatomic) NSString *dateDisplayString; // @synthesize dateDisplayString=_dateDisplayString;
@property(retain, nonatomic) OCPeakMetersView *peakMetersView; // @synthesize peakMetersView=_peakMetersView;
@property(retain, nonatomic) OCArtworkView *albumArtImageView; // @synthesize albumArtImageView=_albumArtImageView;
@property(retain, nonatomic) OCFeedItem *item; // @synthesize item=_item;
@property(nonatomic) __weak id <OCEpisodeCellDownloadDelegate> downloadDelegate; // @synthesize downloadDelegate=_downloadDelegate;
@property(nonatomic) __weak id <OCEpisodeCellInfoDelegate> infoDelegate; // @synthesize infoDelegate=_infoDelegate;
- (void).cxx_destruct;
- (void)configureWithFeedItem:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)assignDefaultDurationDisplayStringForItem:(id)arg1;
- (void)updateStatusLabel;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)didTransitionToState:(unsigned int)arg1;
- (void)willTransitionToState:(unsigned int)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
- (void)downloadRetryButtonTapped:(id)arg1;
- (void)downloadPauseButtonTapped:(id)arg1;
- (void)infoButtonTapped:(id)arg1;
- (void)currentlyPlayingItemUpdated:(id)arg1;
- (void)nowPlayingTimeUpdated:(id)arg1;
- (void)pauseAllVisualizers:(id)arg1;
- (void)prepareForReuse;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

