//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FCModel.h"

#import "UIActivityItemSource.h"

@class NSError, NSString, NSURL, OCFeed;

@interface OCFeedItem : FCModel <UIActivityItemSource>
{
    BOOL _isTransient;
    BOOL _userAddedManually;
    BOOL _userDeleted;
    BOOL _userWasNotified;
    BOOL _userProgressDirty;
    int _feedID;
    int _firstSeenTime;
    int _publishedTime;
    NSString *_title;
    NSString *_author;
    NSString *_summary;
    NSString *_body;
    NSURL *_url;
    NSURL *_enclosureURL;
    NSString *_enclosureType;
    int _userRecommendedTime;
    int _userProgress;
    int _userProgressSetTime;
    int _eTag;
    int _downloadState;
    int _downloadErrors;
    int _downloadLastErrorTime;
    int _advertisedDuration;
    int _downloadedDuration;
    NSString *_twitterFriendRecommendedUsername;
    NSURL *_twitterFriendRecommendedAvatarURL;
    int _currentDownloadState;
    NSError *_currentDownloadError;
    OCFeed *_cachedFeed;
    long long _id;
    double _currentDownloadProgress;
}

+ (id)itemsFromIDList:(id)arg1;
+ (void)deleteAllItemsInFeedID:(int)arg1;
+ (void)validateDownloadedFiles;
+ (id)itemsWithFailedDownloads;
+ (id)itemsInDownloadQueue;
+ (id)itemSyncArraysForFeedID:(int)arg1 onlyLocallyModifiedItems:(BOOL)arg2;
+ (BOOL)updateFromAPIDictionary:(id)arg1;
+ (id)transientInstancesFromAPIRecommendationArray:(id)arg1 excludeExisting:(BOOL)arg2;
+ (id)transientInstanceFromAPIDictionary:(id)arg1;
+ (id)pathForDownloadedEnclosureWithID:(long long)arg1;
@property(retain, nonatomic) OCFeed *cachedFeed; // @synthesize cachedFeed=_cachedFeed;
@property(retain, nonatomic) NSError *currentDownloadError; // @synthesize currentDownloadError=_currentDownloadError;
@property(nonatomic) int currentDownloadState; // @synthesize currentDownloadState=_currentDownloadState;
@property(nonatomic) double currentDownloadProgress; // @synthesize currentDownloadProgress=_currentDownloadProgress;
@property(retain, nonatomic) NSURL *twitterFriendRecommendedAvatarURL; // @synthesize twitterFriendRecommendedAvatarURL=_twitterFriendRecommendedAvatarURL;
@property(retain, nonatomic) NSString *twitterFriendRecommendedUsername; // @synthesize twitterFriendRecommendedUsername=_twitterFriendRecommendedUsername;
@property(nonatomic) int downloadedDuration; // @synthesize downloadedDuration=_downloadedDuration;
@property(nonatomic) int advertisedDuration; // @synthesize advertisedDuration=_advertisedDuration;
@property(nonatomic) int downloadLastErrorTime; // @synthesize downloadLastErrorTime=_downloadLastErrorTime;
@property(nonatomic) int downloadErrors; // @synthesize downloadErrors=_downloadErrors;
@property(nonatomic) int downloadState; // @synthesize downloadState=_downloadState;
@property(nonatomic) int eTag; // @synthesize eTag=_eTag;
@property(nonatomic) BOOL userProgressDirty; // @synthesize userProgressDirty=_userProgressDirty;
@property(nonatomic) int userProgressSetTime; // @synthesize userProgressSetTime=_userProgressSetTime;
@property(nonatomic) int userProgress; // @synthesize userProgress=_userProgress;
@property(nonatomic) int userRecommendedTime; // @synthesize userRecommendedTime=_userRecommendedTime;
@property(nonatomic) BOOL userWasNotified; // @synthesize userWasNotified=_userWasNotified;
@property(nonatomic) BOOL userDeleted; // @synthesize userDeleted=_userDeleted;
@property(nonatomic) BOOL userAddedManually; // @synthesize userAddedManually=_userAddedManually;
@property(copy, nonatomic) NSString *enclosureType; // @synthesize enclosureType=_enclosureType;
@property(copy, nonatomic) NSURL *enclosureURL; // @synthesize enclosureURL=_enclosureURL;
@property(copy, nonatomic) NSURL *url; // @synthesize url=_url;
@property(copy, nonatomic) NSString *body; // @synthesize body=_body;
@property(copy, nonatomic) NSString *summary; // @synthesize summary=_summary;
@property(copy, nonatomic) NSString *author; // @synthesize author=_author;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) int publishedTime; // @synthesize publishedTime=_publishedTime;
@property(nonatomic) int firstSeenTime; // @synthesize firstSeenTime=_firstSeenTime;
@property(nonatomic) int feedID; // @synthesize feedID=_feedID;
@property(nonatomic) long long id; // @synthesize id=_id;
@property(nonatomic) BOOL isTransient; // @synthesize isTransient=_isTransient;
- (void).cxx_destruct;
- (id)activityViewController:(id)arg1 itemForActivityType:(id)arg2;
- (id)activityViewController:(id)arg1 subjectForActivityType:(id)arg2;
- (id)activityViewControllerPlaceholderItem:(id)arg1;
- (id)activityViewController:(id)arg1 dataTypeIdentifierForActivityType:(id)arg2;
- (id)renderedNotesHTMLForInfoScreen:(BOOL)arg1 webViewSize:(struct CGSize)arg2;
- (void)didInsert;
- (BOOL)shouldInsert;
- (void)updateFieldNames:(id)arg1 fromDictionary:(id)arg2;
- (void)updateFieldsFromDictionary:(id)arg1 exceptFieldNames:(id)arg2;
@property(readonly, nonatomic) NSString *downloadedEnclosurePath;
- (void)download;
- (void)cancelDownloadAndOrDeleteEnclosure;
- (void)userDidDelete:(BOOL)arg1;
- (void)userDidRecommend:(BOOL)arg1;
- (void)userDidListenToTime:(int)arg1;
- (void)userDidAddManually:(BOOL)arg1;
- (void)saveWasRefused;
- (void)saveDidFail;
@property(readonly, nonatomic) NSString *displayTitle;
@property(readonly, nonatomic) OCFeed *feed;
@property(readonly, nonatomic) NSURL *sharingURL;
- (id)valueOfFieldName:(id)arg1 byResolvingReloadConflictWithDatabaseValue:(id)arg2;

@end

