//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FCModel.h"

#import "OCPlaylistItemProvider.h"

@class NSArray, NSString, NSURL, OCFeedItem, UIImage;

@interface OCFeed : FCModel <OCPlaylistItemProvider>
{
    BOOL _isTransient;
    BOOL _isExplicit;
    BOOL _userDeleted;
    BOOL _userSubscribed;
    BOOL _userSendAPNS;
    BOOL _userUseCustomEffects;
    NSURL *_transientThumbnailURL;
    int _id;
    NSURL *_url;
    NSURL *_link;
    NSString *_title;
    NSString *_author;
    NSString *_summary;
    NSString *_subtitle;
    NSURL *_artworkURL;
    int _artworkDownloadTime;
    int _artworkDownloadErrors;
    int _artworkDownloadLastErrorTime;
    NSString *_language;
    NSString *_itemPrefix;
    int _eTag;
    int _lastItemModifiedTime;
    int _maxServerUserUpdateTime;
    int _userItemLimit;
    int _userPlaybackSpeedID;
    int _userEnhancementMode;
    int _userSettingsUpdateTime;
    NSString *_idHash;
    OCFeedItem *_currentlyPlayingItem;
}

+ (id)playlistWithIdentifier:(id)arg1;
+ (id)transientInstancesFromAPIRecommendationArray:(id)arg1 randomizeNew:(BOOL)arg2 excludeExisting:(BOOL)arg3;
+ (void)validateDownloadedArtworkFiles;
+ (id)allFeedsShallowSyncArray;
+ (id)allFeedIDs;
+ (id)feedIDsWithLocallyUpdatedItems;
+ (void)resetDeletedFeedList;
+ (BOOL)updateFromAPIDictionary:(id)arg1;
+ (id)transientInstanceFromAPIDictionary:(id)arg1;
+ (id)feedsFromIDList:(id)arg1;
+ (id)pathForDownloadedArtworkWithURL:(id)arg1;
+ (id)cachedInfo;
+ (CDUnknownBlockType)titleSortComparator;
@property(retain, nonatomic) OCFeedItem *currentlyPlayingItem; // @synthesize currentlyPlayingItem=_currentlyPlayingItem;
@property(copy, nonatomic) NSString *idHash; // @synthesize idHash=_idHash;
@property(nonatomic) int userSettingsUpdateTime; // @synthesize userSettingsUpdateTime=_userSettingsUpdateTime;
@property(nonatomic) int userEnhancementMode; // @synthesize userEnhancementMode=_userEnhancementMode;
@property(nonatomic) int userPlaybackSpeedID; // @synthesize userPlaybackSpeedID=_userPlaybackSpeedID;
@property(nonatomic) BOOL userUseCustomEffects; // @synthesize userUseCustomEffects=_userUseCustomEffects;
@property(nonatomic) int userItemLimit; // @synthesize userItemLimit=_userItemLimit;
@property(nonatomic) BOOL userSendAPNS; // @synthesize userSendAPNS=_userSendAPNS;
@property(nonatomic) BOOL userSubscribed; // @synthesize userSubscribed=_userSubscribed;
@property(nonatomic) BOOL userDeleted; // @synthesize userDeleted=_userDeleted;
@property(nonatomic) int maxServerUserUpdateTime; // @synthesize maxServerUserUpdateTime=_maxServerUserUpdateTime;
@property(nonatomic) int lastItemModifiedTime; // @synthesize lastItemModifiedTime=_lastItemModifiedTime;
@property(nonatomic) int eTag; // @synthesize eTag=_eTag;
@property(nonatomic) BOOL isExplicit; // @synthesize isExplicit=_isExplicit;
@property(copy, nonatomic) NSString *itemPrefix; // @synthesize itemPrefix=_itemPrefix;
@property(copy, nonatomic) NSString *language; // @synthesize language=_language;
@property(nonatomic) int artworkDownloadLastErrorTime; // @synthesize artworkDownloadLastErrorTime=_artworkDownloadLastErrorTime;
@property(nonatomic) int artworkDownloadErrors; // @synthesize artworkDownloadErrors=_artworkDownloadErrors;
@property(nonatomic) int artworkDownloadTime; // @synthesize artworkDownloadTime=_artworkDownloadTime;
@property(copy, nonatomic) NSURL *artworkURL; // @synthesize artworkURL=_artworkURL;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(copy, nonatomic) NSString *summary; // @synthesize summary=_summary;
@property(copy, nonatomic) NSString *author; // @synthesize author=_author;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSURL *link; // @synthesize link=_link;
@property(copy, nonatomic) NSURL *url; // @synthesize url=_url;
@property(nonatomic) int id; // @synthesize id=_id;
@property(copy, nonatomic) NSURL *transientThumbnailURL; // @synthesize transientThumbnailURL=_transientThumbnailURL;
@property(nonatomic) BOOL isTransient; // @synthesize isTransient=_isTransient;
- (void).cxx_destruct;
- (id)nextPlaylistItem;
- (id)playlistItems;
- (id)playlistIdentifier;
@property(readonly, nonatomic) NSArray *allItemsIncludingUndownloaded;
- (void)userDidDelete;
- (void)didDelete;
- (BOOL)shouldDelete;
- (BOOL)shouldUpdate;
- (BOOL)shouldInsert;
- (id)deepSyncArray;
@property(readonly, nonatomic) UIImage *artworkImage;
@property(readonly, nonatomic) NSString *downloadedArtworkPath;
@property(readonly, nonatomic) int cachedNewestUnplayedItemTime;
@property(readonly, nonatomic) int cachedOldestUnplayedItemTime;
@property(readonly, nonatomic) int cachedUnplayedItems;
- (id)valueOfFieldName:(id)arg1 byResolvingReloadConflictWithDatabaseValue:(id)arg2;

@end

