//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSArray, NSString, UIActivityIndicatorView;

@interface OCImportOPMLViewController : UIViewController
{
    NSString *_opmlToImport;
    NSArray *_iTunesDataToImport;
    UIActivityIndicatorView *_spinner;
}

@property(retain, nonatomic) UIActivityIndicatorView *spinner; // @synthesize spinner=_spinner;
@property(copy, nonatomic) NSArray *iTunesDataToImport; // @synthesize iTunesDataToImport=_iTunesDataToImport;
@property(copy, nonatomic) NSString *opmlToImport; // @synthesize opmlToImport=_opmlToImport;
- (void).cxx_destruct;
- (void)viewDidLoad;
- (id)initWithOPML:(id)arg1 orITunesPodcastData:(id)arg2;

@end

