//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "OCStyledLabel.h"

@class NSString, NSTimer;

@interface OCLockedEffectsPromoLabel : OCStyledLabel
{
    NSString *_defaultText;
    NSTimer *_updateTimer;
}

+ (id)label;
@property(retain, nonatomic) NSTimer *updateTimer; // @synthesize updateTimer=_updateTimer;
@property(retain, nonatomic) NSString *defaultText; // @synthesize defaultText=_defaultText;
- (void).cxx_destruct;
- (void)update:(id)arg1;
- (void)dealloc;
- (void)initIfNecessaryFromNib:(BOOL)arg1;

@end

