//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class OCArtworkView, OCBorderedButton, OCStyledLabel, OCTimeRemainingLabel, UIButton, UIColor, UIProgressView;

@interface OCMiniplayer : UIView
{
    float playIconHeight;
    float seekIconHeight;
    BOOL hasActiveItem;
    UIColor *_iconColor;
    OCArtworkView *_art;
    UIView *_artBorder;
    UIButton *_artButton;
    UIButton *_farRightButton;
    UIButton *_playPauseButton;
    UIButton *_seekBackButton;
    UIButton *_seekForwardButton;
    OCTimeRemainingLabel *_timeRemainingLabel;
    UIProgressView *_progressView;
    OCStyledLabel *_nothingPlayingLabel;
    OCBorderedButton *_customButton;
    CDUnknownBlockType _customButtonAction;
}

+ (id)toolbarItems;
+ (id)sharedInstance;
@property(copy, nonatomic) CDUnknownBlockType customButtonAction; // @synthesize customButtonAction=_customButtonAction;
@property(retain, nonatomic) OCBorderedButton *customButton; // @synthesize customButton=_customButton;
@property(retain, nonatomic) OCStyledLabel *nothingPlayingLabel; // @synthesize nothingPlayingLabel=_nothingPlayingLabel;
@property(retain, nonatomic) UIProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) OCTimeRemainingLabel *timeRemainingLabel; // @synthesize timeRemainingLabel=_timeRemainingLabel;
@property(retain, nonatomic) UIButton *seekForwardButton; // @synthesize seekForwardButton=_seekForwardButton;
@property(retain, nonatomic) UIButton *seekBackButton; // @synthesize seekBackButton=_seekBackButton;
@property(retain, nonatomic) UIButton *playPauseButton; // @synthesize playPauseButton=_playPauseButton;
@property(retain, nonatomic) UIButton *farRightButton; // @synthesize farRightButton=_farRightButton;
@property(retain, nonatomic) UIButton *artButton; // @synthesize artButton=_artButton;
@property(retain, nonatomic) UIView *artBorder; // @synthesize artBorder=_artBorder;
@property(retain, nonatomic) OCArtworkView *art; // @synthesize art=_art;
@property(retain, nonatomic) UIColor *iconColor; // @synthesize iconColor=_iconColor;
- (void).cxx_destruct;
- (BOOL)accessibilityActivate;
- (void)artworkTapped:(id)arg1;
- (void)updateNowPlayingItem:(id)arg1;
- (void)setNowPlayingItem:(id)arg1;
- (void)seekForwardButtonTapped:(id)arg1;
- (void)seekBackButtonTapped:(id)arg1;
- (void)playPauseButtonTapped:(id)arg1;
- (void)updatePlayPauseIcon:(id)arg1;
- (void)updateProgress:(id)arg1;
- (void)updateStatusMessage:(id)arg1;
- (void)updateFromUserPreferences:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)customButtonTapped:(id)arg1;
- (void)setCustomButtonWithTitle:(id)arg1 action:(CDUnknownBlockType)arg2;

@end

