//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FCTableViewControllerWithDeselectionFix.h"

#import "OCEpisodeCellInfoDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, OCPlaylist;

@interface OCPlaylistViewController : FCTableViewControllerWithDeselectionFix <UITableViewDataSource, UITableViewDelegate, OCEpisodeCellInfoDelegate>
{
    BOOL animatingDelete;
    BOOL isPurchaseLimited;
    OCPlaylist *_playlist;
    NSArray *_items;
}

@property(copy, nonatomic) NSArray *items; // @synthesize items=_items;
@property(retain, nonatomic) OCPlaylist *playlist; // @synthesize playlist=_playlist;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (BOOL)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)infoButtonTappedInEpisodeCell:(id)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)editPlaylistButtonTapped:(id)arg1;
- (void)editButtonTapped:(id)arg1;
- (void)viewDidLoad;
- (void)refreshCompleted:(id)arg1;
- (void)refreshControlRefreshed:(id)arg1;
- (void)reloadItems:(id)arg1;
- (void)dealloc;
- (id)initWithPlaylist:(id)arg1;

@end

