//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSOrderedSet, OCFeedItem;

@protocol OCPlaylistItemProvider <NSObject>
+ (id)playlistWithIdentifier:(id)arg1;
@property(retain, nonatomic) OCFeedItem *currentlyPlayingItem;
- (NSOrderedSet *)playlistItems;
- (OCFeedItem *)nextPlaylistItem;
- (id)playlistIdentifier;
@end

