//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray;

@interface OCPlayViewControllerView : UIView
{
    NSArray *_pre_iOS8_accessibilityElementOrder;
}

@property(copy, nonatomic) NSArray *pre_iOS8_accessibilityElementOrder; // @synthesize pre_iOS8_accessibilityElementOrder=_pre_iOS8_accessibilityElementOrder;
- (void).cxx_destruct;
- (int)indexOfAccessibilityElement:(id)arg1;
- (int)accessibilityElementCount;
- (id)accessibilityElementAtIndex:(int)arg1;

@end

