//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FCModel.h"

#import "OCPlaylistItemProvider.h"

@class NSArray, NSOrderedSet, NSString, OCFeedItem;

@interface OCPlaylist : FCModel <OCPlaylistItemProvider>
{
    BOOL _userDeleted;
    BOOL _didEverSync;
    NSString *_id;
    NSString *_title;
    NSString *_includedFeedIDList;
    NSString *_excludedFeedIDList;
    NSString *_priorityFeedIDList;
    NSString *_includedItemIDList;
    NSString *_excludedItemIDList;
    NSString *_manualSort;
    int _sortMode;
    int _itemStatus;
    int _userUpdateTimeWindow;
    int _eTag;
    int _userUpdateTime;
    OCFeedItem *_currentlyPlayingItem;
    NSOrderedSet *_playlistItemsWithoutPurchaseLimit;
}

+ (id)playlistWithIdentifier:(id)arg1;
+ (id)playlistSyncArrays:(out char *)arg1;
+ (BOOL)updateFromAPIDictionary:(id)arg1;
@property(retain, nonatomic) NSOrderedSet *playlistItemsWithoutPurchaseLimit; // @synthesize playlistItemsWithoutPurchaseLimit=_playlistItemsWithoutPurchaseLimit;
@property(retain, nonatomic) OCFeedItem *currentlyPlayingItem; // @synthesize currentlyPlayingItem=_currentlyPlayingItem;
@property(nonatomic) int userUpdateTime; // @synthesize userUpdateTime=_userUpdateTime;
@property(nonatomic) int eTag; // @synthesize eTag=_eTag;
@property(nonatomic) BOOL didEverSync; // @synthesize didEverSync=_didEverSync;
@property(nonatomic) BOOL userDeleted; // @synthesize userDeleted=_userDeleted;
@property(nonatomic) int userUpdateTimeWindow; // @synthesize userUpdateTimeWindow=_userUpdateTimeWindow;
@property(nonatomic) int itemStatus; // @synthesize itemStatus=_itemStatus;
@property(nonatomic) int sortMode; // @synthesize sortMode=_sortMode;
@property(copy, nonatomic) NSString *manualSort; // @synthesize manualSort=_manualSort;
@property(copy, nonatomic) NSString *excludedItemIDList; // @synthesize excludedItemIDList=_excludedItemIDList;
@property(copy, nonatomic) NSString *includedItemIDList; // @synthesize includedItemIDList=_includedItemIDList;
@property(copy, nonatomic) NSString *priorityFeedIDList; // @synthesize priorityFeedIDList=_priorityFeedIDList;
@property(copy, nonatomic) NSString *excludedFeedIDList; // @synthesize excludedFeedIDList=_excludedFeedIDList;
@property(copy, nonatomic) NSString *includedFeedIDList; // @synthesize includedFeedIDList=_includedFeedIDList;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *id; // @synthesize id=_id;
- (void).cxx_destruct;
- (id)nextPlaylistItem;
- (id)playlistItems;
- (id)playlistIdentifier;
@property(readonly, nonatomic) unsigned int cachedPlaylistItemCount;
- (unsigned int)bestPositionForItem:(id)arg1 priority:(unsigned int)arg2 inOrderedSet:(id)arg3 feedPriorities:(id)arg4 reverseChronological:(BOOL)arg5 restrictedToOffsets:(id)arg6 overrideTimestampsForOffsets:(id)arg7;
- (unsigned int)bestPositionForItem:(id)arg1 inOrderedSet:(id)arg2 feedPriorities:(id)arg3 reverseChronological:(BOOL)arg4 groupByFeed:(BOOL)arg5;
- (id)sortedItems;
- (id)qualifyingItems;
- (void)userDidChangeManualSortToArray:(id)arg1;
@property(copy, nonatomic) NSArray *excludedItems;
@property(copy, nonatomic) NSArray *includedItems;
@property(copy, nonatomic) NSArray *priorityFeeds;
@property(copy, nonatomic) NSArray *excludedFeeds;
@property(copy, nonatomic) NSArray *includedFeeds;
- (void)userDidDelete;
- (void)userDidUpdate;
- (int)save;
- (id)valueOfFieldName:(id)arg1 byResolvingReloadConflictWithDatabaseValue:(id)arg2;

@end

