//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIViewController;

@interface OCPurchasePromoBar : UIView
{
    CDUnknownBlockType _customAction;
    UIViewController *_presentFromViewController;
}

@property(nonatomic) __weak UIViewController *presentFromViewController; // @synthesize presentFromViewController=_presentFromViewController;
@property(copy, nonatomic) CDUnknownBlockType customAction; // @synthesize customAction=_customAction;
- (void).cxx_destruct;
- (void)tapped:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 presentFromViewController:(id)arg2 limitationMessage:(id)arg3 buttonTitle:(id)arg4;

@end

