//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MPRemoteCommandCenter;

@interface OCRemoteCommandCenter : NSObject
{
    MPRemoteCommandCenter *_remoteCommandCenter;
}

@property(retain, nonatomic) MPRemoteCommandCenter *remoteCommandCenter; // @synthesize remoteCommandCenter=_remoteCommandCenter;
- (void).cxx_destruct;
- (int)changePlaybackRate:(id)arg1;
- (int)pause:(id)arg1;
- (int)play:(id)arg1;
- (int)skipForward:(id)arg1;
- (int)skipBackward:(id)arg1;
- (void)updateFromUserPreferences:(id)arg1;
- (void)dealloc;
- (id)init;

@end

