//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class NSMutableArray, UISlider;

@interface OCSpeedControl : UIControl
{
    unsigned int currentSpeedIndex;
    UISlider *_slider;
    NSMutableArray *_speedLabels;
}

@property(retain, nonatomic) NSMutableArray *speedLabels; // @synthesize speedLabels=_speedLabels;
@property(retain, nonatomic) UISlider *slider; // @synthesize slider=_slider;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)sliderValueChanged:(id)arg1;
- (void)speedChanged:(id)arg1;
- (void)dealloc;
- (id)init;

@end

