//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

@class NSString;

@interface OCStyledLabel : UILabel
{
    BOOL didInit;
    NSString *_fontTextStyle;
    float _fontSizeAdjustment;
    float _forcedFontSize;
    NSString *_untransformedText;
    struct UIEdgeInsets _edgeInsets;
}

+ (id)labelWithFontTextStyle:(id)arg1 sizeAdjustment:(float)arg2;
+ (id)labelWithFontTextStyle:(id)arg1 forcedSize:(float)arg2;
+ (id)labelWithFontTextStyle:(id)arg1;
@property(retain, nonatomic) NSString *untransformedText; // @synthesize untransformedText=_untransformedText;
@property(nonatomic) struct UIEdgeInsets edgeInsets; // @synthesize edgeInsets=_edgeInsets;
@property(nonatomic) float forcedFontSize; // @synthesize forcedFontSize=_forcedFontSize;
@property(nonatomic) float fontSizeAdjustment; // @synthesize fontSizeAdjustment=_fontSizeAdjustment;
@property(retain, nonatomic) NSString *fontTextStyle; // @synthesize fontTextStyle=_fontTextStyle;
- (void).cxx_destruct;
- (void)drawTextInRect:(struct CGRect)arg1;
- (struct CGRect)textRectForBounds:(struct CGRect)arg1 limitedToNumberOfLines:(int)arg2;
- (void)updateFont;
- (void)setText:(id)arg1;
- (id)text;
- (void)systemFontCategoryChanged:(id)arg1;
- (void)dealloc;
- (void)awakeFromNib;
- (id)init;
- (void)initIfNecessaryFromNib:(BOOL)arg1;

@end

