//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@interface UIColor (FCUtilities)
+ (id)fc_colorWithHexString:(id)arg1;
- (id)fc_CSSColor;
- (id)fc_colorByModifyingHSBA:(CDUnknownBlockType)arg1;
- (id)fc_colorByModifyingRGBA:(CDUnknownBlockType)arg1;
@end

