//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (FCUtilities)
+ (id)fc_imageWithSize:(struct CGSize)arg1 drawing:(CDUnknownBlockType)arg2;
+ (id)fc_maskedImageNamed:(id)arg1 color:(id)arg2;
+ (id)fc_solidColorImageWithSize:(struct CGSize)arg1 color:(id)arg2;
+ (id)fc_stretchableImageWithSolidColor:(id)arg1;
- (id)fc_imageWithAdditionalDrawing:(CDUnknownBlockType)arg1;
- (id)fc_tintedImageUsingColor:(id)arg1;
- (id)fc_desaturatedImage;
@end

