//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (CompactConstraint)
- (void)addConstraintsWithVisualFormat:(id)arg1 options:(unsigned int)arg2 metrics:(id)arg3 views:(id)arg4;
- (id)addCompactConstraints:(id)arg1 metrics:(id)arg2 views:(id)arg3;
- (id)addCompactConstraint:(id)arg1 metrics:(id)arg2 views:(id)arg3;
@end

