//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSURLRequest, UIImage;

@protocol AFImageCache
- (void)cacheImage:(UIImage *)arg1 forRequest:(NSURLRequest *)arg2;
- (UIImage *)cachedImageForRequest:(NSURLRequest *)arg1;
@end

