//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIActionSheet.h"

#import "UIActionSheetDelegate.h"

@class NSMutableArray;

@interface FCActionSheet : UIActionSheet <UIActionSheetDelegate>
{
    CDUnknownBlockType _cancelButtonBlock;
    CDUnknownBlockType _destructiveButtonBlock;
    CDUnknownBlockType _dismissalBlock;
    NSMutableArray *_otherButtonBlocks;
    NSMutableArray *_otherButtonIndexes;
}

+ (void)dismissAll;
@property(retain, nonatomic) NSMutableArray *otherButtonIndexes; // @synthesize otherButtonIndexes=_otherButtonIndexes;
@property(retain, nonatomic) NSMutableArray *otherButtonBlocks; // @synthesize otherButtonBlocks=_otherButtonBlocks;
@property(copy, nonatomic) CDUnknownBlockType dismissalBlock; // @synthesize dismissalBlock=_dismissalBlock;
@property(copy, nonatomic) CDUnknownBlockType destructiveButtonBlock; // @synthesize destructiveButtonBlock=_destructiveButtonBlock;
@property(copy, nonatomic) CDUnknownBlockType cancelButtonBlock; // @synthesize cancelButtonBlock=_cancelButtonBlock;
- (void).cxx_destruct;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)willPresentActionSheet:(id)arg1;
- (void)callDismissBlock:(id)arg1;
- (void)addDestructiveButtonWithTitle:(id)arg1 action:(CDUnknownBlockType)arg2;
- (void)addCancelButtonWithTitle:(id)arg1 action:(CDUnknownBlockType)arg2;
- (void)addCancelButtonWithAction:(CDUnknownBlockType)arg1;
- (void)addButtonWithTitle:(id)arg1 action:(CDUnknownBlockType)arg2;
- (void)setDismissedAction:(CDUnknownBlockType)arg1;
- (id)initWithTitle:(id)arg1;

@end

