//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSMutableSet, NSObject<OS_dispatch_queue>, NSTimer;

@interface FCClassInstanceCounter : NSObject
{
    NSMutableDictionary *_classes;
    NSMutableDictionary *_classLimits;
    NSMutableSet *_classesExceedingLimit;
    NSObject<OS_dispatch_queue> *_queue;
    NSTimer *_pollingTimer;
}

+ (void)trackInstance:(id)arg1 withClassInstanceLimit:(int)arg2 identifier:(id)arg3;
+ (id)sharedInstance;
@property(retain, nonatomic) NSTimer *pollingTimer; // @synthesize pollingTimer=_pollingTimer;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSMutableSet *classesExceedingLimit; // @synthesize classesExceedingLimit=_classesExceedingLimit;
@property(retain, nonatomic) NSMutableDictionary *classLimits; // @synthesize classLimits=_classLimits;
@property(retain, nonatomic) NSMutableDictionary *classes; // @synthesize classes=_classes;
- (void).cxx_destruct;
- (void)pollingTimerFired:(id)arg1;
- (id)init;

@end

