//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@interface FCQueueOperation : NSOperation
{
    CDUnknownBlockType _actionBlock;
    long long _opcode;
}

@property(copy, nonatomic) CDUnknownBlockType actionBlock; // @synthesize actionBlock=_actionBlock;
@property(nonatomic) long long opcode; // @synthesize opcode=_opcode;
- (void).cxx_destruct;
- (void)main;

@end

