//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FCReachability : NSObject
{
    BOOL isOnline;
    BOOL requireWiFi;
    struct __SCNetworkReachability *reachability;
    BOOL _isOnlineViaWiFi;
    int _status;
    unsigned int _reachabilityFlags;
}

@property(nonatomic) unsigned int reachabilityFlags; // @synthesize reachabilityFlags=_reachabilityFlags;
@property(nonatomic) int status; // @synthesize status=_status;
@property(readonly, nonatomic) BOOL isOnlineViaWiFi; // @synthesize isOnlineViaWiFi=_isOnlineViaWiFi;
- (void)dealloc;
- (void)setReachabilityHostname:(id)arg1;
- (BOOL)internetConnectionIsOfflineForError:(id)arg1;
- (void)update;
@property(nonatomic) BOOL allowCellular;
@property(readonly, nonatomic) BOOL isOnline;
- (id)initWithHostname:(id)arg1 allowCellular:(BOOL)arg2;

@end

