//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface Lockbox : NSObject
{
}

+ (id)dateForKey:(id)arg1;
+ (BOOL)setDate:(id)arg1 forKey:(id)arg2 accessibility:(void *)arg3;
+ (BOOL)setDate:(id)arg1 forKey:(id)arg2;
+ (id)dictionaryForKey:(id)arg1;
+ (BOOL)setDictionary:(id)arg1 forKey:(id)arg2 accessibility:(void *)arg3;
+ (BOOL)setDictionary:(id)arg1 forKey:(id)arg2;
+ (id)setForKey:(id)arg1;
+ (BOOL)setSet:(id)arg1 forKey:(id)arg2 accessibility:(void *)arg3;
+ (BOOL)setSet:(id)arg1 forKey:(id)arg2;
+ (id)arrayForKey:(id)arg1;
+ (BOOL)setArray:(id)arg1 forKey:(id)arg2 accessibility:(void *)arg3;
+ (BOOL)setArray:(id)arg1 forKey:(id)arg2;
+ (id)stringForKey:(id)arg1;
+ (BOOL)setString:(id)arg1 forKey:(id)arg2 accessibility:(void *)arg3;
+ (BOOL)setString:(id)arg1 forKey:(id)arg2;
+ (id)objectForKey:(id)arg1;
+ (BOOL)setObject:(id)arg1 forKey:(id)arg2 accessibility:(void *)arg3;
+ (id)_hierarchicalKey:(id)arg1;
+ (id)_query;
+ (id)_service;
+ (void)initialize;

@end

