//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (FCUtilities)
+ (id)fc_randomDataWithLength:(unsigned int)arg1;
- (id)fc_inflatedDataWithHeader:(BOOL)arg1;
- (id)fc_deflatedData;
- (id)fc_hexString;
- (id)fc_MD5Digest;
- (id)fc_stringValue;
@end

