//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSLayoutConstraint.h"

@interface NSLayoutConstraint (CompactConstraint)
+ (id)compactConstraint:(id)arg1 metrics:(id)arg2 views:(id)arg3 self:(id)arg4;
+ (id)compactConstraint:(id)arg1 metrics:(id)arg2 views:(id)arg3;
+ (id)compactConstraints:(id)arg1 metrics:(id)arg2 views:(id)arg3 self:(id)arg4;
+ (id)compactConstraints:(id)arg1 metrics:(id)arg2 views:(id)arg3;
@end

