//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (FCUtilities)
- (id)fc_MD5Digest;
- (id)fc_hexString;
- (id)fc_trimSubstringFromBothEnds:(id)arg1;
- (id)fc_trimSubstringFromEnd:(id)arg1;
- (id)fc_trimSubstringFromStart:(id)arg1;
- (BOOL)fc_contains:(id)arg1;
- (id)fc_substringBetween:(id)arg1 and:(id)arg2;
- (id)fc_substringBefore:(id)arg1 fromEnd:(BOOL)arg2;
- (id)fc_substringAfter:(id)arg1 fromEnd:(BOOL)arg2;
- (id)fc_summarizeToLength:(int)arg1 withEllipsis:(BOOL)arg2;
- (id)fc_HTMLEncodedString;
- (id)fc_URLEncodedString;
@end

