//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIColor;

@interface OCAppearance : NSObject
{
    UIColor *_mainTintColor;
    UIColor *_alternateTintColor;
    UIColor *_addActionTintColor;
    UIColor *_destructiveActionTintColor;
    UIColor *_tableViewSeparatorColor;
    UIColor *_textColor;
    UIColor *_lightTextColor;
    UIColor *_tableViewSectionHeaderBackgroundColor;
    UIColor *_tableViewSectionHeaderTextColor;
    UIColor *_groupedTableViewBackgroundColor;
    NSString *_boldMainFontName;
    NSString *_mainFontName;
    NSString *_webFontFamilyName;
    NSString *_boldSmallFontName;
    NSString *_smallFontName;
    float _fontSizeAdjustment;
}

+ (id)logoImageWithWidth:(float)arg1 color:(id)arg2 backgroundColor:(id)arg3;
+ (id)lockIconWithWidth:(float)arg1 color:(id)arg2;
+ (id)seekIconWithHeight:(float)arg1 forwardDirection:(BOOL)arg2 interval:(int)arg3 color:(id)arg4;
+ (id)recommendIconWithHeight:(float)arg1 color:(id)arg2 filled:(BOOL)arg3;
+ (id)addPlaylistIconWithHeight:(float)arg1 color:(id)arg2;
+ (id)detailDisclosureIconWithHeight:(float)arg1 color:(id)arg2;
+ (id)pauseDownloadIconWithHeight:(float)arg1 color:(id)arg2;
+ (id)downloadIconWithHeight:(float)arg1 color:(id)arg2;
+ (id)downloadsToolbarIconWithHeight:(float)arg1 color:(id)arg2 numberOfActiveDownloads:(unsigned int)arg3 numberOfFailedDownloads:(unsigned int)arg4;
+ (id)settingsIcon;
+ (id)preferredFontWithTextStyle:(id)arg1 sizeAdjustment:(float)arg2;
+ (id)preferredFontWithTextStyle:(id)arg1 forcedSize:(float)arg2;
+ (float)preferredFontSizeForTextStyle:(id)arg1;
+ (id)preferredFontWithTextStyle:(id)arg1;
+ (id)textAttributesForTextStyle:(id)arg1;
+ (id)textAttributesForTextStyle:(id)arg1 forcedSize:(float)arg2;
+ (id)preferredFontDescriptorWithTextStyle:(id)arg1;
+ (id)defaultParagraphStyleForTextStyle:(id)arg1;
+ (id)defaultColorForTextStyle:(id)arg1;
+ (id)fontNameForTextStyle:(id)arg1;
+ (id)transformedText:(id)arg1 forTextStyle:(id)arg2;
+ (void)setSystemAppearance;
+ (id)appearance;
@property(nonatomic) float fontSizeAdjustment; // @synthesize fontSizeAdjustment=_fontSizeAdjustment;
@property(copy, nonatomic) NSString *smallFontName; // @synthesize smallFontName=_smallFontName;
@property(copy, nonatomic) NSString *boldSmallFontName; // @synthesize boldSmallFontName=_boldSmallFontName;
@property(copy, nonatomic) NSString *webFontFamilyName; // @synthesize webFontFamilyName=_webFontFamilyName;
@property(copy, nonatomic) NSString *mainFontName; // @synthesize mainFontName=_mainFontName;
@property(copy, nonatomic) NSString *boldMainFontName; // @synthesize boldMainFontName=_boldMainFontName;
@property(retain, nonatomic) UIColor *groupedTableViewBackgroundColor; // @synthesize groupedTableViewBackgroundColor=_groupedTableViewBackgroundColor;
@property(retain, nonatomic) UIColor *tableViewSectionHeaderTextColor; // @synthesize tableViewSectionHeaderTextColor=_tableViewSectionHeaderTextColor;
@property(retain, nonatomic) UIColor *tableViewSectionHeaderBackgroundColor; // @synthesize tableViewSectionHeaderBackgroundColor=_tableViewSectionHeaderBackgroundColor;
@property(retain, nonatomic) UIColor *lightTextColor; // @synthesize lightTextColor=_lightTextColor;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(retain, nonatomic) UIColor *tableViewSeparatorColor; // @synthesize tableViewSeparatorColor=_tableViewSeparatorColor;
@property(retain, nonatomic) UIColor *destructiveActionTintColor; // @synthesize destructiveActionTintColor=_destructiveActionTintColor;
@property(retain, nonatomic) UIColor *addActionTintColor; // @synthesize addActionTintColor=_addActionTintColor;
@property(retain, nonatomic) UIColor *alternateTintColor; // @synthesize alternateTintColor=_alternateTintColor;
@property(retain, nonatomic) UIColor *mainTintColor; // @synthesize mainTintColor=_mainTintColor;
- (void).cxx_destruct;
- (float)fontSizeAdjustmentForTextStyle:(id)arg1;
- (id)init;

@end

