//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIResponder.h"

#import "UIApplicationDelegate.h"

@class FCReachability, OCDownloader, OCLoginOrRegisterViewController, OCPodcastsViewController, OCRemoteCommandCenter, OCStoreRegionalDistrictAssistantManager, OCSyncQueue, UINavigationController, UIWindow;

@interface OCAppDelegate : UIResponder <UIApplicationDelegate>
{
    BOOL _loggedIn;
    UIWindow *_window;
    UINavigationController *_navigationController;
    UINavigationController *_loginNavigationController;
    UINavigationController *_tourViewController;
    OCPodcastsViewController *_podcastsViewController;
    FCReachability *_reachability;
    OCSyncQueue *_syncQueue;
    OCDownloader *_downloader;
    OCRemoteCommandCenter *_remoteCommandCenter;
    OCStoreRegionalDistrictAssistantManager *_purchaseManager;
    OCLoginOrRegisterViewController *_loginViewController;
}

+ (id)databasePath;
@property(retain, nonatomic) OCLoginOrRegisterViewController *loginViewController; // @synthesize loginViewController=_loginViewController;
@property(retain, nonatomic) OCStoreRegionalDistrictAssistantManager *purchaseManager; // @synthesize purchaseManager=_purchaseManager;
@property(retain, nonatomic) OCRemoteCommandCenter *remoteCommandCenter; // @synthesize remoteCommandCenter=_remoteCommandCenter;
@property(retain, nonatomic) OCDownloader *downloader; // @synthesize downloader=_downloader;
@property(retain, nonatomic) OCSyncQueue *syncQueue; // @synthesize syncQueue=_syncQueue;
@property(nonatomic, getter=isLoggedIn) BOOL loggedIn; // @synthesize loggedIn=_loggedIn;
@property(retain, nonatomic) FCReachability *reachability; // @synthesize reachability=_reachability;
@property(retain, nonatomic) OCPodcastsViewController *podcastsViewController; // @synthesize podcastsViewController=_podcastsViewController;
@property(retain, nonatomic) UINavigationController *tourViewController; // @synthesize tourViewController=_tourViewController;
@property(retain, nonatomic) UINavigationController *loginNavigationController; // @synthesize loginNavigationController=_loginNavigationController;
@property(retain, nonatomic) UINavigationController *navigationController; // @synthesize navigationController=_navigationController;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (void)showInternetConnectionOfflineAlert;
- (void)logOutUserSession;
- (void)startLoggedInUserSessionWithNewUserDictionary:(id)arg1;
- (void)navigateToLoggedOutEnvironmentAnimated:(BOOL)arg1 logoutInProgress:(BOOL)arg2;
- (void)navigateToLoggedInEnvironmentAnimated:(BOOL)arg1 showTour:(BOOL)arg2;
- (void)application:(id)arg1 performFetchWithCompletionHandler:(CDUnknownBlockType)arg2;
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2 fetchCompletionHandler:(CDUnknownBlockType)arg3;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (void)handlePush:(id)arg1 fetchCompletionHandler:(CDUnknownBlockType)arg2;
- (void)showLocalNotificationForItem:(id)arg1;
- (void)remoteControlReceivedWithEvent:(id)arg1;
- (void)application:(id)arg1 handleEventsForBackgroundURLSession:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (BOOL)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)promptToAddURLSearchString:(id)arg1 xCallbackSuccessURL:(id)arg2 xCallbackCancelURL:(id)arg3;
- (BOOL)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;

@end

