//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class OCAudioFilePlayer;

@protocol OCAudioFilePlayerDelegate <NSObject>
- (void)audioFilePlayerDidReachEndOfFile:(OCAudioFilePlayer *)arg1;
- (void)audioFilePlayerDidReachNewTimestamp:(OCAudioFilePlayer *)arg1;
- (void)audioFilePlayerDidSeek:(OCAudioFilePlayer *)arg1;
@end

