//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class OCAudioFilePlayer, OCPlaybackSpeed;

@interface OCAudioGraph : NSObject
{
    struct OpaqueAUGraph *_graph;
    struct OpaqueAudioComponentInstance *_mixer;
    struct OpaqueAudioComponentInstance *_iPodTime;
    struct OpaqueAudioComponentInstance *_equalizer;
    struct OpaqueAudioComponentInstance *_compressor;
    struct OpaqueAudioComponentInstance *_output;
    struct AudioStreamBasicDescription _outputStreamFormat;
    long mixerNode;
    int currentEnhancementMode;
    OCPlaybackSpeed *currentPlaybackSpeed;
    double playbackSpeed;
    int channels;
    float sourceAudioBuffer[2][10240];
    float silenceDetectionBuffer[2][10240];
    float silenceCrossfadeMultipliersL[46];
    BOOL renderOffline;
    BOOL offlineRenderComplete;
    BOOL silenceSkipperEnabled;
    int silenceSkipperAmount;
    unsigned int silentFramesSkippedSinceLastSave;
    OCAudioFilePlayer *_filePlayer;
    double _sampleRate;
}

@property(nonatomic) double sampleRate; // @synthesize sampleRate=_sampleRate;
@property(retain, nonatomic) OCAudioFilePlayer *filePlayer; // @synthesize filePlayer=_filePlayer;
- (void).cxx_destruct;
@property(nonatomic) int enhancementMode;
@property(retain, nonatomic) OCPlaybackSpeed *playbackSpeed;
@property(readonly, nonatomic) int channels;
- (void)seekToFrame:(long long)arg1;
@property(readonly, nonatomic) BOOL isPlaying;
- (void)stop;
- (void)start;
- (double)getAndResetSkippedSilenceDuration;
- (void)dealloc;
- (id)initWithFileReader:(id)arg1 forOfflineRendering:(BOOL)arg2;

@end

