//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_semaphore>, NSOperationQueue, OCAudioFileReader;

@interface OCAudioFilePlayer : NSObject
{
    struct {
        void *buffer;
        int length;
        int tail;
        int head;
        int fillCount;
    } circularBuffer;
    BOOL reachedEOF;
    BOOL notifiedDelegateOfEOF;
    BOOL drainingQueue;
    float **readBuffer;
    int lastReportedTimestamp;
    BOOL waitingForProduction;
    int sourceChannels;
    long long startingFrame;
    long long clientReadOffsetFromStartingFrame;
    float speedometerSeconds[16];
    int speedometerOffset;
    int speedometerNumSeconds;
    double speedometerLastRealTimestamp;
    double speedometerLastMediaTimestamp;
    float averageSpeed;
    NSObject<OS_dispatch_semaphore> *producerDeallocSemaphore;
    NSObject<OS_dispatch_semaphore> *consumerDeallocSemaphore;
    double sampleRate;
    OCAudioFileReader *_fileReader;
    id <OCAudioFilePlayerDelegate> _delegate;
    NSOperationQueue *_productionQueue;
    double _currentTimestamp;
}

@property(retain, nonatomic) NSOperationQueue *productionQueue; // @synthesize productionQueue=_productionQueue;
@property(nonatomic) __weak id <OCAudioFilePlayerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) OCAudioFileReader *fileReader; // @synthesize fileReader=_fileReader;
@property(nonatomic) double currentTimestamp; // @synthesize currentTimestamp=_currentTimestamp;
- (void).cxx_destruct;
- (void)seekToFrame:(long long)arg1;
@property(readonly, nonatomic) long long approximateCurrentFrame;
- (void)resetRealSpeed;
@property(readonly, nonatomic) double currentRealSpeed;
- (unsigned long)readSamples:(long long)arg1 intoArray:(float **)arg2 channels:(int)arg3;
- (void)produce;
- (void)setDraining;
- (void)dealloc;
- (id)initWithFileReader:(id)arg1;

@end

