//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewController.h"

#import "UICollectionViewDelegateFlowLayout.h"
#import "UISearchDisplayDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSString, UISearchBar, UISearchDisplayController;

@interface OCBrowsePodcastsController : UICollectionViewController <UICollectionViewDelegateFlowLayout, UITableViewDataSource, UITableViewDelegate, UISearchDisplayDelegate>
{
    UISearchBar *_searchBar;
    UISearchDisplayController *_activeSearchDisplayController;
    NSArray *_currentSearchResults;
    NSString *_currentSearchQuery;
    NSArray *_directoryCategories;
}

+ (id)normalizedSearchQueryFromString:(id)arg1;
@property(copy, nonatomic) NSArray *directoryCategories; // @synthesize directoryCategories=_directoryCategories;
@property(copy, nonatomic) NSString *currentSearchQuery; // @synthesize currentSearchQuery=_currentSearchQuery;
@property(copy, nonatomic) NSArray *currentSearchResults; // @synthesize currentSearchResults=_currentSearchResults;
@property(retain, nonatomic) UISearchDisplayController *activeSearchDisplayController; // @synthesize activeSearchDisplayController=_activeSearchDisplayController;
@property(retain, nonatomic) UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (int)numberOfSectionsInCollectionView:(id)arg1;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(int)arg3;
- (void)customizeNoResultsLabelForSearchDisplayController:(id)arg1;
- (BOOL)searchDisplayController:(id)arg1 shouldReloadTableForSearchString:(id)arg2;
- (void)beginSearchWithQuery:(id)arg1;
- (void)addURLButtonTapped:(id)arg1;
- (void)cancelButtonTapped:(id)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

@end

