//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FCTableViewControllerWithDeselectionFix.h"

@class NSArray;

@interface OCDirectoryCategoryViewController : FCTableViewControllerWithDeselectionFix
{
    NSArray *_feeds;
}

@property(copy, nonatomic) NSArray *feeds; // @synthesize feeds=_feeds;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)subscribeAll:(id)arg1;
- (void)viewDidLoad;
- (id)initWithCategoryTitle:(id)arg1 feeds:(id)arg2;

@end

