//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FCTableViewControllerWithDeselectionFix.h"

@class NSArray, NSSet;

@interface OCEpisodeMultiPickerViewController : FCTableViewControllerWithDeselectionFix
{
    NSArray *_items;
    NSSet *_initiallySelectedItems;
    CDUnknownBlockType _selectionChangeBlock;
}

@property(copy, nonatomic) CDUnknownBlockType selectionChangeBlock; // @synthesize selectionChangeBlock=_selectionChangeBlock;
@property(copy, nonatomic) NSSet *initiallySelectedItems; // @synthesize initiallySelectedItems=_initiallySelectedItems;
@property(copy, nonatomic) NSArray *items; // @synthesize items=_items;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (void)selectionDidChange;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidLoad;
- (id)initWithTitle:(id)arg1 items:(id)arg2 selectedItems:(id)arg3 selectionChangeBlock:(CDUnknownBlockType)arg4;

@end

