//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSString, OCArtworkView, OCFeed, OCPeakMetersView, OCStyledLabel, OCViewStack;

@interface OCFeedCell : UITableViewCell
{
    OCArtworkView *_albumArtImageView;
    NSString *_artworkIdentifier;
    OCViewStack *_viewStack;
    OCStyledLabel *_titleLabel;
    OCStyledLabel *_authorLabel;
    OCPeakMetersView *_peakMetersView;
    OCFeed *_feed;
}

+ (void)setVisualizersPaused:(BOOL)arg1;
+ (float)standardHeight;
@property(retain, nonatomic) OCFeed *feed; // @synthesize feed=_feed;
@property(retain, nonatomic) OCPeakMetersView *peakMetersView; // @synthesize peakMetersView=_peakMetersView;
@property(retain, nonatomic) OCStyledLabel *authorLabel; // @synthesize authorLabel=_authorLabel;
@property(retain, nonatomic) OCStyledLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) OCViewStack *viewStack; // @synthesize viewStack=_viewStack;
@property(copy, nonatomic) NSString *artworkIdentifier; // @synthesize artworkIdentifier=_artworkIdentifier;
@property(retain, nonatomic) OCArtworkView *albumArtImageView; // @synthesize albumArtImageView=_albumArtImageView;
- (void).cxx_destruct;
- (void)currentlyPlayingItemUpdated:(id)arg1;
- (void)pauseAllVisualizers:(id)arg1;
- (void)configureWithPodcast:(id)arg1 hasUnplayedEpisodes:(BOOL)arg2;
- (void)prepareForReuse;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

