//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITextFieldDelegate.h"

@class OCBorderedButton, OCButton, UIActivityIndicatorView, UITextField;

@interface OCLoginViewController : UIViewController <UITextFieldDelegate>
{
    UITextField *_emailField;
    UITextField *_passwordField;
    UIActivityIndicatorView *_spinner;
    OCBorderedButton *_logInButton;
    OCButton *_forgotPasswordButton;
    int _accountMode;
}

@property(nonatomic) int accountMode; // @synthesize accountMode=_accountMode;
@property(retain, nonatomic) OCButton *forgotPasswordButton; // @synthesize forgotPasswordButton=_forgotPasswordButton;
@property(retain, nonatomic) OCBorderedButton *logInButton; // @synthesize logInButton=_logInButton;
@property(retain, nonatomic) UIActivityIndicatorView *spinner; // @synthesize spinner=_spinner;
@property(retain, nonatomic) UITextField *passwordField; // @synthesize passwordField=_passwordField;
@property(retain, nonatomic) UITextField *emailField; // @synthesize emailField=_emailField;
- (void).cxx_destruct;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)showDialogForConnectionError:(id)arg1;
- (void)sendLoginAttemptWithRegistration:(BOOL)arg1 processResult:(CDUnknownBlockType)arg2 connectionError:(CDUnknownBlockType)arg3;
- (void)sendLoginRequest;
- (void)stopLoadingUI;
- (void)startLoadingUI;
- (void)forgotPasswordButtonTapped:(id)arg1;
- (void)logInButtonTapped:(id)arg1;
- (BOOL)basicLocalValidationIncludingPassword:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithMode:(int)arg1;

@end

