//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIWebViewDelegate.h"

@class NSURL, OCStyledLabel, OCViewStack, UIWebView;

@interface OCMinibrowserViewController : UIViewController <UIWebViewDelegate>
{
    int loadsInProgress;
    BOOL hasNavigatedToSubsequentPage;
    NSURL *_currentURL;
    UIWebView *_webView;
    OCViewStack *_titleStack;
    OCStyledLabel *_titleLabel;
    OCStyledLabel *_urlLabel;
}

@property(retain, nonatomic) OCStyledLabel *urlLabel; // @synthesize urlLabel=_urlLabel;
@property(retain, nonatomic) OCStyledLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) OCViewStack *titleStack; // @synthesize titleStack=_titleStack;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
@property(retain, nonatomic) NSURL *currentURL; // @synthesize currentURL=_currentURL;
- (void).cxx_destruct;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3;
- (void)shareButtonTapped:(id)arg1;
- (void)updateTitleWithURL:(id)arg1;
- (void)dealloc;
- (void)viewDidLoad;
- (id)initWithURL:(id)arg1;

@end

