//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITextFieldDelegate.h"

@class NSString, OCBorderedButton, UIActivityIndicatorView, UITextField;

@interface OCPasswordResetViewController : UIViewController <UITextFieldDelegate>
{
    UITextField *_passwordField;
    UIActivityIndicatorView *_spinner;
    OCBorderedButton *_submitButton;
    NSString *_resetToken;
}

@property(retain, nonatomic) NSString *resetToken; // @synthesize resetToken=_resetToken;
@property(retain, nonatomic) OCBorderedButton *submitButton; // @synthesize submitButton=_submitButton;
@property(retain, nonatomic) UIActivityIndicatorView *spinner; // @synthesize spinner=_spinner;
@property(retain, nonatomic) UITextField *passwordField; // @synthesize passwordField=_passwordField;
- (void).cxx_destruct;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (BOOL)basicLocalValidation;
- (void)submitButtonTapped:(id)arg1;
- (void)sendResetRequestVerifyOnly:(BOOL)arg1;
- (void)stopLoadingUI;
- (void)startLoadingUI;
- (void)viewDidLoad;
- (id)initWithResetToken:(id)arg1;

@end

