//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CADisplayLink, NSMapTable;

@interface OCPeakMetersManager : NSObject
{
    NSMapTable *_animatingInstances;
    CADisplayLink *_displayLink;
}

+ (void)reset;
+ (void)updateWithBuffer:(float *)arg1 numSamples:(unsigned int)arg2;
+ (BOOL)needsUpdates;
+ (void)setSampleRate:(float)arg1;
+ (id)sharedInstance;
@property(retain, nonatomic) CADisplayLink *displayLink; // @synthesize displayLink=_displayLink;
@property(retain, nonatomic) NSMapTable *animatingInstances; // @synthesize animatingInstances=_animatingInstances;
- (void).cxx_destruct;
- (void)updateBars;
- (void)setNeedsUpdates:(BOOL)arg1;
- (void)removeAnimatingInstance:(id)arg1;
- (void)addAnimatingInstance:(id)arg1;
- (id)init;

@end

