//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface OCPeakMetersView : UIView
{
    BOOL _useBoldColors;
}

@property(nonatomic) BOOL useBoldColors; // @synthesize useBoldColors=_useBoldColors;
- (void)endUpdates;
- (void)beginUpdates;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;
- (void)jeff;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)awakeFromNib;

@end

