//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FCPickerViewController.h"

@interface OCPickerViewController : FCPickerViewController
{
}

- (void)configureCell:(id)arg1 withItem:(id)arg2;
- (void)configureTableView:(id)arg1 withCellReuseIdentifier:(id)arg2;

@end

