//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface OCPlaybackSpeed : NSObject <NSCopying>
{
    BOOL _labelIsSignificant;
    int _speedID;
    NSString *_labelText;
    double _playbackRate;
    double _silenceSkipRatio;
}

+ (id)allSpeeds;
+ (id)defaultSpeed;
+ (id)speedWithID:(int)arg1;
@property(nonatomic) BOOL labelIsSignificant; // @synthesize labelIsSignificant=_labelIsSignificant;
@property(copy, nonatomic) NSString *labelText; // @synthesize labelText=_labelText;
@property(nonatomic) double silenceSkipRatio; // @synthesize silenceSkipRatio=_silenceSkipRatio;
@property(nonatomic) double playbackRate; // @synthesize playbackRate=_playbackRate;
@property(nonatomic) int speedID; // @synthesize speedID=_speedID;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

