//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIScrollViewDelegate.h"
#import "UIWebViewDelegate.h"

@class MPVolumeView, OCArtworkView, OCButton, OCFeedItem, OCPeakMetersView, OCProgressSlider, OCStyledLabel, OCViewStack, UIButton, UIColor, UILabel, UIView, UIWebView;

@interface OCPlayViewController : UIViewController <UIWebViewDelegate, UIScrollViewDelegate>
{
    BOOL configured;
    BOOL _pageControlUsed;
    float mainControlsIconHeight;
    float playPauseIconHeight;
    BOOL _accessibilityShouldFocusTitleOnViewDidAppear;
    BOOL _artLoaded;
    BOOL _webViewLoaded;
    OCStyledLabel *_titleBarShowLabel;
    OCStyledLabel *_titleBarEpisodeLabel;
    UILabel *_elapsedLabel;
    UILabel *_remainingLabel;
    OCProgressSlider *_progressSlider;
    OCArtworkView *_albumArt;
    UIWebView *_notesWebView;
    UIView *_volumeViewContainer;
    UIView *_playbackControls;
    OCButton *_effectsButton;
    OCButton *_playbackModesButton;
    UIButton *_playPauseButton;
    UIButton *_skipBackButton;
    UIButton *_skipForwardButton;
    OCPeakMetersView *_peakMeters;
    OCFeedItem *_item;
    UIColor *_mainControlsIconColor;
    MPVolumeView *_volumeView;
    OCViewStack *_titleStack;
}

@property(retain, nonatomic) OCViewStack *titleStack; // @synthesize titleStack=_titleStack;
@property(nonatomic) BOOL webViewLoaded; // @synthesize webViewLoaded=_webViewLoaded;
@property(nonatomic) BOOL artLoaded; // @synthesize artLoaded=_artLoaded;
@property(retain, nonatomic) MPVolumeView *volumeView; // @synthesize volumeView=_volumeView;
@property(retain, nonatomic) UIColor *mainControlsIconColor; // @synthesize mainControlsIconColor=_mainControlsIconColor;
@property(retain, nonatomic) OCFeedItem *item; // @synthesize item=_item;
@property(nonatomic) BOOL accessibilityShouldFocusTitleOnViewDidAppear; // @synthesize accessibilityShouldFocusTitleOnViewDidAppear=_accessibilityShouldFocusTitleOnViewDidAppear;
@property(retain, nonatomic) OCPeakMetersView *peakMeters; // @synthesize peakMeters=_peakMeters;
@property(retain, nonatomic) UIButton *skipForwardButton; // @synthesize skipForwardButton=_skipForwardButton;
@property(retain, nonatomic) UIButton *skipBackButton; // @synthesize skipBackButton=_skipBackButton;
@property(retain, nonatomic) UIButton *playPauseButton; // @synthesize playPauseButton=_playPauseButton;
@property(retain, nonatomic) OCButton *playbackModesButton; // @synthesize playbackModesButton=_playbackModesButton;
@property(retain, nonatomic) OCButton *effectsButton; // @synthesize effectsButton=_effectsButton;
@property(retain, nonatomic) UIView *playbackControls; // @synthesize playbackControls=_playbackControls;
@property(retain, nonatomic) UIView *volumeViewContainer; // @synthesize volumeViewContainer=_volumeViewContainer;
@property(retain, nonatomic) UIWebView *notesWebView; // @synthesize notesWebView=_notesWebView;
@property(retain, nonatomic) OCArtworkView *albumArt; // @synthesize albumArt=_albumArt;
@property(retain, nonatomic) OCProgressSlider *progressSlider; // @synthesize progressSlider=_progressSlider;
@property(retain, nonatomic) UILabel *remainingLabel; // @synthesize remainingLabel=_remainingLabel;
@property(retain, nonatomic) UILabel *elapsedLabel; // @synthesize elapsedLabel=_elapsedLabel;
@property(retain, nonatomic) OCStyledLabel *titleBarEpisodeLabel; // @synthesize titleBarEpisodeLabel=_titleBarEpisodeLabel;
@property(retain, nonatomic) OCStyledLabel *titleBarShowLabel; // @synthesize titleBarShowLabel=_titleBarShowLabel;
- (void).cxx_destruct;
- (BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3;
- (void)itemRecommendationChanged:(id)arg1;
- (void)effectsControlsButtonTapped:(id)arg1;
- (void)playbackModesButtonTapped:(id)arg1;
- (void)continuousPlayModeChanged:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (void)globalSettingsToggleChanged:(id)arg1;
- (void)skipForwardButtonTapped:(id)arg1;
- (void)skipBackButtonTapped:(id)arg1;
- (void)playPauseButtonTapped:(id)arg1;
- (void)shareButtonTapped:(id)arg1;
- (void)showArtAndNotesIfBothLoaded;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)configureWithItem:(id)arg1;
- (void)updateItem:(id)arg1;
- (void)updateAirPlayAvailability:(id)arg1;
- (void)updatePlayPauseIcon:(id)arg1;
- (void)contentSizeChanged:(id)arg1;
- (void)dealloc;
- (id)initWithFeedItem:(id)arg1;

@end

