//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class OCPeakMetersView, OCPlaylist, UILabel;

@interface OCPlaylistCell : UITableViewCell
{
    UILabel *_titleLabel;
    OCPeakMetersView *_peakMetersView;
    OCPlaylist *_playlist;
}

+ (void)setVisualizersPaused:(BOOL)arg1;
+ (float)standardHeight;
@property(retain, nonatomic) OCPlaylist *playlist; // @synthesize playlist=_playlist;
@property(retain, nonatomic) OCPeakMetersView *peakMetersView; // @synthesize peakMetersView=_peakMetersView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)currentlyPlayingItemUpdated:(id)arg1;
- (void)pauseAllVisualizers:(id)arg1;
- (void)configureWithPlaylist:(id)arg1;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

