//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FCTableViewControllerWithDeselectionFix.h"

#import "OCEpisodeCellInfoDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, OCFeed, OCSegmentedControlBar, OCViewStack, UIImage;

@interface OCPodcastViewController : FCTableViewControllerWithDeselectionFix <UITableViewDataSource, UITableViewDelegate, OCEpisodeCellInfoDelegate>
{
    int mode;
    BOOL animatingDelete;
    BOOL isUploadsFeed;
    BOOL isFetchingItems;
    OCFeed *_feed;
    NSArray *_items;
    NSArray *_episodeLimitLabels;
    NSArray *_episodeLimitValues;
    OCSegmentedControlBar *_allEpisodesToggle;
    OCViewStack *_descriptionBlock;
    float _descriptionBlockNormalHeight;
    UIImage *_segmentImageUnplayedSortAsc;
    UIImage *_segmentImageUnplayedSortDesc;
    UIImage *_segmentImageUnplayedSortNone;
    UIImage *_segmentImageAllSortAsc;
    UIImage *_segmentImageAllSortDesc;
    UIImage *_segmentImageAllSortNone;
}

@property(retain, nonatomic) UIImage *segmentImageAllSortNone; // @synthesize segmentImageAllSortNone=_segmentImageAllSortNone;
@property(retain, nonatomic) UIImage *segmentImageAllSortDesc; // @synthesize segmentImageAllSortDesc=_segmentImageAllSortDesc;
@property(retain, nonatomic) UIImage *segmentImageAllSortAsc; // @synthesize segmentImageAllSortAsc=_segmentImageAllSortAsc;
@property(retain, nonatomic) UIImage *segmentImageUnplayedSortNone; // @synthesize segmentImageUnplayedSortNone=_segmentImageUnplayedSortNone;
@property(retain, nonatomic) UIImage *segmentImageUnplayedSortDesc; // @synthesize segmentImageUnplayedSortDesc=_segmentImageUnplayedSortDesc;
@property(retain, nonatomic) UIImage *segmentImageUnplayedSortAsc; // @synthesize segmentImageUnplayedSortAsc=_segmentImageUnplayedSortAsc;
@property(nonatomic) float descriptionBlockNormalHeight; // @synthesize descriptionBlockNormalHeight=_descriptionBlockNormalHeight;
@property(retain, nonatomic) OCViewStack *descriptionBlock; // @synthesize descriptionBlock=_descriptionBlock;
@property(retain, nonatomic) OCSegmentedControlBar *allEpisodesToggle; // @synthesize allEpisodesToggle=_allEpisodesToggle;
@property(copy, nonatomic) NSArray *episodeLimitValues; // @synthesize episodeLimitValues=_episodeLimitValues;
@property(copy, nonatomic) NSArray *episodeLimitLabels; // @synthesize episodeLimitLabels=_episodeLimitLabels;
@property(copy) NSArray *items; // @synthesize items=_items;
@property(retain, nonatomic) OCFeed *feed; // @synthesize feed=_feed;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)infoButtonTappedInEpisodeCell:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)addPodcastModeEpisodeDownloadButtonTapped:(id)arg1;
- (void)subscribeButtonTapped:(id)arg1;
- (void)addFeedWithSpecificItem:(id)arg1 sender:(id)arg2;
- (unsigned int)indexOfCurrentEpisodeLimitValue;
- (id)currentEpisodeLimitLabelText;
- (void)episodeLimitStepperChanged:(id)arg1;
- (void)pushNotificationsSwitchToggled:(id)arg1;
- (void)subscribeSwitchToggled:(id)arg1;
- (void)subscribePromoButtonTapped:(id)arg1;
- (void)deleteButtonTapped:(id)arg1;
- (void)allEpisodesToggleChanged:(id)arg1;
- (void)allEpisodesTouchedSelectedSegment:(id)arg1;
- (void)setSubscribePromoViewIfNotSubscribed;
- (void)toggleDescriptionBlockExpanded:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)refreshCompleted:(id)arg1;
- (void)refreshControlRefreshed:(id)arg1;
- (void)reloadItems;
- (void)feedItemsChanged:(id)arg1;
- (void)dealloc;
- (id)initWithFeed:(id)arg1;

@end

