//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UISlider.h"

@interface OCProgressSlider : UISlider
{
    BOOL shouldAnimateTintChanges;
    long long touchesBeganWithItemID;
    long long currentItemID;
}

- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (struct CGRect)thumbRectForBounds:(struct CGRect)arg1 trackRect:(struct CGRect)arg2 value:(float)arg3;
- (struct CGRect)trackRectForBounds:(struct CGRect)arg1;
- (struct CGRect)minimumValueImageRectForBounds:(struct CGRect)arg1;
- (struct CGRect)maximumValueImageRectForBounds:(struct CGRect)arg1;
- (id)accessibilityValue;
- (void)accessibilityDecrement;
- (void)accessibilityIncrement;
- (void)commitChange;
- (void)valueChanged:(id)arg1;
- (void)update:(id)arg1;
- (void)itemUpdated:(id)arg1;
- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
- (void)tintColorDidChange;
- (void)registerObservers;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

@end

