//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UISegmentedControl.h"

@interface OCSleepTimerSegmentedControl : UISegmentedControl
{
}

- (void)valueChanged:(id)arg1;
- (void)update:(id)arg1;
- (void)dealloc;
- (id)init;

@end

