//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class OCSyncQueue;

@interface OCSyncOperation : NSOperation
{
    BOOL _wasUserInitiated;
    OCSyncQueue *_syncQueue;
}

@property(nonatomic) __weak OCSyncQueue *syncQueue; // @synthesize syncQueue=_syncQueue;
@property(nonatomic) BOOL wasUserInitiated; // @synthesize wasUserInitiated=_wasUserInitiated;
- (void).cxx_destruct;
- (void)main;
- (id)initWithSyncQueue:(id)arg1 wasUserInitiated:(BOOL)arg2;

@end

