//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperationQueue.h"

@class NSString;

@interface OCSyncQueue : NSOperationQueue
{
    BOOL _isLoggedOut;
    NSString *_statusMessageForDisplay;
    CDUnknownBlockType _backgroundFetchCompletionHandler;
    long _lastSyncTime;
}

@property(nonatomic) long lastSyncTime; // @synthesize lastSyncTime=_lastSyncTime;
@property(copy, nonatomic) CDUnknownBlockType backgroundFetchCompletionHandler; // @synthesize backgroundFetchCompletionHandler=_backgroundFetchCompletionHandler;
@property(nonatomic) BOOL isLoggedOut; // @synthesize isLoggedOut=_isLoggedOut;
@property(copy, nonatomic) NSString *statusMessageForDisplay; // @synthesize statusMessageForDisplay=_statusMessageForDisplay;
- (void).cxx_destruct;
- (BOOL)processObjectArrayFromServer:(id)arg1 writeFeedIDsNeedingUpdatesIntoArray:(id)arg2;
- (BOOL)processObjectArrayFromServer:(id)arg1;
- (void)userInitiatedSync;
- (void)syncIfItHasBeenAWhile;
- (void)sync;
- (void)dealloc;
- (id)init;

@end

