//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "OCDirectoryCategoryCollectionViewCell.h"

@class OCBorderedButton, OCStyledLabel;

@interface OCTwitterDirectoryCollectionViewCell : OCDirectoryCategoryCollectionViewCell
{
    BOOL isLoggedIntoTwitter;
    CDUnknownBlockType _loginButtonAction;
    OCBorderedButton *_twitterPromoButton;
    OCStyledLabel *_twitterPromoLabel;
}

+ (int)rows;
+ (int)columns;
@property(retain, nonatomic) OCStyledLabel *twitterPromoLabel; // @synthesize twitterPromoLabel=_twitterPromoLabel;
@property(retain, nonatomic) OCBorderedButton *twitterPromoButton; // @synthesize twitterPromoButton=_twitterPromoButton;
@property(copy, nonatomic) CDUnknownBlockType loginButtonAction; // @synthesize loginButtonAction=_loginButtonAction;
- (void).cxx_destruct;
- (void)twitterLoginButtonTapped:(id)arg1;
- (void)twitterDataChanged:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

