//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class OCBorderedButton, OCStyledLabel, UIActivityIndicatorView, UIImageView, UIView;

@interface OCTwitterLoginViewController : UIViewController
{
    UIView *_overlay;
    UIActivityIndicatorView *_loadingSpinner;
    OCBorderedButton *_logIntoTwitterButton;
    OCStyledLabel *_logIntoTwitterLabel;
    UIImageView *_logIntoTwitterRecommendIcon;
    OCStyledLabel *_logIntoTwitterFooterLabel;
    OCStyledLabel *_logIntoTwitterReadOnlyReassuranceLabel;
}

+ (void)requestAccessWithCompletion:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) OCStyledLabel *logIntoTwitterReadOnlyReassuranceLabel; // @synthesize logIntoTwitterReadOnlyReassuranceLabel=_logIntoTwitterReadOnlyReassuranceLabel;
@property(retain, nonatomic) OCStyledLabel *logIntoTwitterFooterLabel; // @synthesize logIntoTwitterFooterLabel=_logIntoTwitterFooterLabel;
@property(retain, nonatomic) UIImageView *logIntoTwitterRecommendIcon; // @synthesize logIntoTwitterRecommendIcon=_logIntoTwitterRecommendIcon;
@property(retain, nonatomic) OCStyledLabel *logIntoTwitterLabel; // @synthesize logIntoTwitterLabel=_logIntoTwitterLabel;
@property(retain, nonatomic) OCBorderedButton *logIntoTwitterButton; // @synthesize logIntoTwitterButton=_logIntoTwitterButton;
@property(retain, nonatomic) UIActivityIndicatorView *loadingSpinner; // @synthesize loadingSpinner=_loadingSpinner;
@property(retain, nonatomic) UIView *overlay; // @synthesize overlay=_overlay;
- (void).cxx_destruct;
- (void)showNotLoggedInInterface;
- (void)showLoadingInterface;
- (void)viewDidLoad;
- (void)dismiss;
- (void)logIntoTwitter:(id)arg1;
- (id)init;

@end

