//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray, NSString;

@interface OCViewStack : UIView
{
    NSString *_accessibilityLabelPrefix;
    UIView *_stackContainer;
    NSMutableArray *_stackedSubviews;
    NSMutableArray *_topPaddings;
    NSMutableArray *_maxLines;
    NSMutableArray *_stackConstraints;
}

@property(retain, nonatomic) NSMutableArray *stackConstraints; // @synthesize stackConstraints=_stackConstraints;
@property(retain, nonatomic) NSMutableArray *maxLines; // @synthesize maxLines=_maxLines;
@property(retain, nonatomic) NSMutableArray *topPaddings; // @synthesize topPaddings=_topPaddings;
@property(retain, nonatomic) NSMutableArray *stackedSubviews; // @synthesize stackedSubviews=_stackedSubviews;
@property(retain, nonatomic) UIView *stackContainer; // @synthesize stackContainer=_stackContainer;
@property(copy, nonatomic) NSString *accessibilityLabelPrefix; // @synthesize accessibilityLabelPrefix=_accessibilityLabelPrefix;
- (void).cxx_destruct;
- (void)setBounds:(struct CGRect)arg1;
- (void)updateConstraints;
- (void)invalidateStackConstraints;
- (void)layoutSubviews;
- (float)heightToDisplayAllLines;
- (void)updateAccessibilityLabel;
- (void)addStackedSubview:(id)arg1 withTopPadding:(float)arg2;
- (id)addStackedLabelWithFontTextStyle:(id)arg1 maximumLines:(int)arg2 topPadding:(float)arg3;
- (id)addStackedLabelWithFontTextStyle:(id)arg1 maximumLines:(int)arg2;

@end

