//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class AFHTTPRequestOperation;

@interface UIButton (_AFNetworking)
+ (id)af_sharedImageRequestOperationQueue;
@property(retain, nonatomic, setter=af_setBackgroundImageRequestOperation:) AFHTTPRequestOperation *af_backgroundImageRequestOperation;
@property(retain, nonatomic, setter=af_setImageRequestOperation:) AFHTTPRequestOperation *af_imageRequestOperation;
@end

